#	Copyright 2016-2017, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: custom
env: flex
service: lighthouse-machine
automatic_scaling:
  min_num_instances: 6
  max_num_instances: 8
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /.*
  script: IGNORED
  secure: always

liveness_check:
   path: '/_ah/health'
   check_interval_sec: 30
   timeout_sec: 4
   failure_threshold: 3
   success_threshold: 2
   initial_delay_sec: 60

readiness_check:
  path: '/_ah/busy'
  check_interval_sec: 3
  timeout_sec: 2
  failure_threshold: 1
  success_threshold: 1
  app_start_timeout_sec: 300

network:
  instance_tag: lighthouse-machine
